# Assignment no 14
# Abdul Moiz

In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn=sql.connect("database.sqlite")

In [3]:
conn

In [4]:
pd.read_sql_query('select * from sqlite_master',conn)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...
1,index,salaries_year_idx,Salaries,16566,CREATE INDEX salaries_year_idx ON Salaries (Year)

In [5]:
def sql_query(query):
    return pd.read_sql_query(query,conn)

In [6]:
query = """
    select *
    from Salaries
    limit 5
    
"""
sql_query(query)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,,316285.74,316285.74,2011,,San Francisco,

#### **1. What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')**

In [7]:
query = """
    select JobTitle, AVG(TotalPayBenefits) as avg_totalpay
    from Salaries
    where JobTitle not in ('Not Provided', 'Not provided')
    group by JobTitle
    order by avg_totalpay DESC
"""
sql_query(query)

                                            JobTitle   avg_totalpay
0                           Chief Investment Officer  436224.360000
1                                    Chief of Police  411732.266667
2                             Chief, Fire Department  408865.326667
3     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  399211.275000
4                         Gen Mgr, Public Trnsp Dept  380696.440000
...                                              ...            ...
2153                           SPECIAL ASSISTANT XIV     673.800000
2154              BOARD/COMMISSION MEMBER, GROUP III     638.787879
2155                      BdComm Mbr, Grp2,M=$25/Mtg     475.047742
2156               BOARD/COMMISSION MEMBER, GROUP II     296.511628
2157         PUBLIC SAFETY COMMUNICATIONS TECHNICIAN     149.510000

[2158 rows x 2 columns]

#### **2. Show The JobTitle and Overtime Pay for All Employees With Overtime Pay greater than 50000**

In [8]:
query = """
    select JobTitle, OvertimePay 
    from Salaries
    where OvertimePay > 50000
"""
sql_query(query)

                                              JobTitle   OvertimePay
0                      CAPTAIN III (POLICE DEPARTMENT)     106088.18
1                 WIRE ROPE CABLE MAINTENANCE MECHANIC      56120.71
2                   BATTALION CHIEF, (FIRE DEPARTMENT)       89062.9
3                   BATTALION CHIEF, (FIRE DEPARTMENT)      86362.68
4     ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)      71344.88
...                                                ...           ...
2163                           Parking Control Officer      54738.36
2164                                      Not provided  Not Provided
2165                                      Not provided  Not Provided
2166                                      Not provided  Not Provided
2167                                      Not provided  Not Provided

[2168 rows x 2 columns]

#### **3. What is the total number of unique employees? exclude ('Not Provided', 'Not provided')**

In [9]:
query = """
    select count(distinct EmployeeName) as unique_employee_count
    from Salaries
    where EmployeeName not in ('Not Provided', 'Not provided')
  
"""
sql_query(query)

   unique_employee_count
0                 110808

#### **4.Show The Top 10 highest Paid Employees**

In [10]:
query = """
    select employeename,jobtitle,totalpaybenefits
    from Salaries
    where EmployeeName not in ('Not Provided', 'Not provided')
    order by totalpaybenefits desc 
    limit 10
  
"""
sql_query(query)

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
5,Joanne M Hayes-White,"Chief, Fire Department",422353.40
6,Gregory P Suhr,Chief of Police,418019.22
7,Joanne M Hayes-White,"Chief, Fire Department",417435.10
8,Ellen G Moffatt,Asst Med Examiner,415767.94
9,Gary Altenberg,"Lieutenant, Fire Suppression",407274.78

#### **5.Show All Employees Ordered By Their TotalPay Benefits In Descending Order**

In [11]:
query = """
    select employeename,jobtitle,totalpaybenefits
    from Salaries
    where EmployeeName not in ('Not Provided', 'Not provided')
    order by totalpaybenefits desc 
"""
sql_query(query)

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
...,...,...,...
148642,Roy I Tillery,Custodian,0.00
148643,Timothy E Gibson,Police Officer 3,-2.73
148644,Mark E Laherty,Police Officer 3,-8.20
148645,David P Kucia,Police Officer 3,-33.89
148646,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13